# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yanaaaa
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-yana-test
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-project

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-offline

functions:
  createTable:
    handler: handler.createTable
    events:
      - httpApi:
          path: /create
          method: post

  getUsers:
    handler: handler.getUsers
    events:
      - httpApi:
          path: /users
          method: get

  getUserById:
    handler: handler.getUserById
    events:
      - httpApi:
          path: /users/{id}
          method: get

  bye:
    handler: handler.bye
    events:
      - httpApi:
          path: /bye
          method: get
